### ISSUE TITLE
Issue #1: Installing SFML and Dependencies 

### ISSUE THREAD

**Issue by CaptainBrexit** [lucy-musicalfish/CodingForDucks#1]
Attempted to install SFML and setup geany make sequence using minGW, but could not complete make commands due to issues with 'makefile' and 'sfml1.cpp' files.

**Comment by lucy-musicalfish** [comment]
Solution Option: 
Email Arthur, attend a lab session ASAP and ask a tutor

**Comment by CaptainBrexit** [comment]
Update to issue: Solved compiler issues, now have 'missing files' issues
Planned Solution: Get help from tutor

**Comment by CaptainBrexit** [comment]
Update to Issue: Solved
Cause of Issue: File 'libstdc++-6.dll' needed to be copied from MinGW folder to AVC_Robot and AVC_Server folders
